name: Testing
on: push

jobs: 
  test_projects: 
    runs-on: ubuntu-latest
    setps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run:
        pip3 install --user django
        python3 manage.py test 